
#version 450
#extension GL_ARB_gpu_shader_fp64 : require

#define dSzWorkgroup 7

layout (local_size_x = dSzWorkgroup, local_size_y = 1, local_size_z = 1 ) in;

layout(std430, binding = 0) buffer buf
{
	uint buff[];
};

layout(push_constant) uniform Params
{
	uint numElements;
} params;

void main()
{
	uint idx = gl_GlobalInvocationID.x;

	if(idx >= params.numElements)
		return;

	buff[idx] = idx + 2;
}

